/*
 * Subset of Influx API covered by Influx CLI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// Functions struct for Functions
type Functions struct {
	Functions *[]Function `json:"functions,omitempty" yaml:"functions,omitempty"`
}

// NewFunctions instantiates a new Functions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFunctions() *Functions {
	this := Functions{}
	return &this
}

// NewFunctionsWithDefaults instantiates a new Functions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFunctionsWithDefaults() *Functions {
	this := Functions{}
	return &this
}

// GetFunctions returns the Functions field value if set, zero value otherwise.
func (o *Functions) GetFunctions() []Function {
	if o == nil || o.Functions == nil {
		var ret []Function
		return ret
	}
	return *o.Functions
}

// GetFunctionsOk returns a tuple with the Functions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Functions) GetFunctionsOk() (*[]Function, bool) {
	if o == nil || o.Functions == nil {
		return nil, false
	}
	return o.Functions, true
}

// HasFunctions returns a boolean if a field has been set.
func (o *Functions) HasFunctions() bool {
	if o != nil && o.Functions != nil {
		return true
	}

	return false
}

// SetFunctions gets a reference to the given []Function and assigns it to the Functions field.
func (o *Functions) SetFunctions(v []Function) {
	o.Functions = &v
}

func (o Functions) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Functions != nil {
		toSerialize["functions"] = o.Functions
	}
	return json.Marshal(toSerialize)
}

type NullableFunctions struct {
	value *Functions
	isSet bool
}

func (v NullableFunctions) Get() *Functions {
	return v.value
}

func (v *NullableFunctions) Set(val *Functions) {
	v.value = val
	v.isSet = true
}

func (v NullableFunctions) IsSet() bool {
	return v.isSet
}

func (v *NullableFunctions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFunctions(val *Functions) *NullableFunctions {
	return &NullableFunctions{value: val, isSet: true}
}

func (v NullableFunctions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFunctions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
